@startuml
'https://plantuml.com/class-diagram

javafx.application <|-- theApp
javafx.application -- theListController
theListController -- ToDoListTableManagement
theListController -- ToDoListItemManagement
theListController -- ToDoListItem
theListController -- ToDoListFiles

class theApp {
+main()
+start()
}

class theListController {
+buttonAddItem()
+buttonRemoveItem()
+buttonChangeStatus()
+buttonShowIncomplete()
+buttonShowComplete()
+buttonShowAll()
+buttonSaveList()
+buttonLoadList()
+buttonClearList()
+buttonBrowse()
+changeDueDateColumn()
+changeDescriptionColumn()
+buttonRemoveTab()
}

class ToDoListFiles {
+saveFile()
+loadFile()
+fileWriter()
}

class ToDoListItem {
-itemDescription
-itemStatus
-itemdueDate
+getDescription()
+setDescription()
+getStatus()
+setStatus()
+getDueDate()
+setDueDate()
+toString()
}

class ToDoListItemManagement {
+addItem()
+removeItem()
+time()
+clearList()
+statusChange()
}

class ToDoListTableManagement {
+starter()
+showIncomplete()
+showComplete()
+showAll()
}

@enduml